/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application.views;

import application.dao.CandidateDao;
import application.dao.SelectionDao;
import application.daoimpl.CandidateDaoImpl;
import application.daoimpl.SelectionDaoImpl;
import application.models.CandidateModel;
import application.models.CandidateTableModel;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author mahasiswa unindra 
 */
public class MasterCandidate extends javax.swing.JPanel {
    private final CandidateDao candidateDao;
    private final SelectionDao selectionDao;
    private AddCandidateDialog addCandidateDialog = new AddCandidateDialog(null, true);
    private String id;

    /**
     * Creates new form CandidateView
     */
    public MasterCandidate() {
        initComponents();
        this.candidateDao = new CandidateDaoImpl();
        this.selectionDao = new SelectionDaoImpl();
        this.loadTable();
        buttonEdit.setBackground(Color.white);
        buttonAdd.setBackground(Color.white);
    }
    
    private void getDataTabel(){
        int selectedRow = tableCandidate.getSelectedRow();

        TableModel model = tableCandidate.getModel();
        String id = model.getValueAt(selectedRow, 0).toString();
        String name = model.getValueAt(selectedRow, 1).toString();
        String description = model.getValueAt(selectedRow, 2).toString();
        String appearanceScore = model.getValueAt(selectedRow, 3).toString();
        String comfortScore = model.getValueAt(selectedRow, 4).toString();
        String durabilityScore = model.getValueAt(selectedRow, 5).toString();
        String maintenanceScore = model.getValueAt(selectedRow, 6).toString();
        this.id = id;
        
        addCandidateDialog.setDataTabel(id, name, description, appearanceScore, comfortScore, durabilityScore, maintenanceScore);
    }
    
    public void loadTable() {
        List<CandidateModel> candidates = this.candidateDao.findAll();
        CandidateTableModel candidateTableModel = new CandidateTableModel(candidates);
        
        tableCandidate.setModel(candidateTableModel);
        
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tableCandidate.getModel());
        tableCandidate.setRowSorter(sorter);

        List<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(1, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(2, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(3, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        Panel = new javax.swing.JPanel();
        buttonAdd = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        note = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCandidate = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 247, 250));

        title.setBackground(new java.awt.Color(66, 173, 245));
        title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("  Data Infrastruktur");
        title.setOpaque(true);

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        buttonAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonAdd.setForeground(new java.awt.Color(179, 30, 144));
        buttonAdd.setText("Tambah Data");
        buttonAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 210, 226)));
        buttonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonAddMouseExited(evt);
            }
        });
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonEdit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonEdit.setForeground(new java.awt.Color(179, 30, 144));
        buttonEdit.setText("Ubah");
        buttonEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(202, 210, 226)));
        buttonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonEditMouseExited(evt);
            }
        });
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonDelete.setBackground(new java.awt.Color(179, 30, 114));
        buttonDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonDelete.setText("Hapus");
        buttonDelete.setBorder(null);
        buttonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonDeleteMouseExited(evt);
            }
        });
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        note.setText("Catatan : Edit/Hapus data calon pelamar, klik data pada tabel terlebih dahulu");

        tableCandidate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCandidate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCandidateMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableCandidate);

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(note)
                    .addContainerGap(359, Short.MAX_VALUE)))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLayout.createSequentialGroup()
                    .addGap(265, 265, 265)
                    .addComponent(note)
                    .addGap(0, 158, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(601, 601, 601))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
        addCandidateDialog.setTitleFrame("Tambah Data Bahan");
        addCandidateDialog.clearForm();
        addCandidateDialog.show();
        loadTable();
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here:
        if(id != null){
            addCandidateDialog.setTitleFrame("Ubah Data Bahan");
            addCandidateDialog.show();
            loadTable();
            id = null;
        }else{
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin diUbah! ");
        }
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
        try{
            if(id != null){
                int ok = JOptionPane.showConfirmDialog(null,"hapus","Konfirmasi Dialog",JOptionPane.YES_NO_OPTION);
                if(ok == 0){
                    int deleted = candidateDao.delete(Integer.parseInt(id));
                    if(deleted > 0){
                        JOptionPane.showMessageDialog(null, "Data Berhasil diHapus ");
                        loadTable();
                        System.out.println(id);
                        selectionDao.deleteByUserId(Integer.parseInt(id));

                        id = null;
                        addCandidateDialog.clearForm();
                    }else{
                        JOptionPane.showMessageDialog(this, "Gagal Menghapus Data");
                    }
                }
            }else{
                JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus! ");
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Gagal Menghapus Data");
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEditMouseEntered
        // TODO add your handling code here:
        buttonEdit.setBackground(new Color(250, 239, 245));
    }//GEN-LAST:event_buttonEditMouseEntered

    private void buttonEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEditMouseExited
        // TODO add your handling code here:
        buttonEdit.setBackground(Color.white);
    }//GEN-LAST:event_buttonEditMouseExited

    private void buttonDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDeleteMouseEntered
        // TODO add your handling code here:
        buttonDelete.setBackground(new Color(132, 0, 74));
    }//GEN-LAST:event_buttonDeleteMouseEntered

    private void buttonDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDeleteMouseExited
        // TODO add your handling code here:
        buttonDelete.setBackground(new Color(179, 30, 114));
    }//GEN-LAST:event_buttonDeleteMouseExited

    private void buttonAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddMouseEntered
        // TODO add your handling code here:
        buttonAdd.setBackground(new Color(250, 239, 245));
    }//GEN-LAST:event_buttonAddMouseEntered

    private void buttonAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddMouseExited
        // TODO add your handling code here:
        buttonAdd.setBackground(Color.white);
    }//GEN-LAST:event_buttonAddMouseExited

    private void tableCandidateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCandidateMouseClicked
        // TODO add your handling code here:
        getDataTabel();
    }//GEN-LAST:event_tableCandidateMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel note;
    private javax.swing.JTable tableCandidate;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
